---
title: "Assignment 2"
format: html
editor: visual
---

## Task 1

```{r}
rm(list=ls())
library(tidyverse)
library(rvest)
library(janitor)
library(stringr)
```

```{r}
url <- "https://www.motor.no/aktuelt/motors-store-vintertest-av-rekkevidde-pa-elbiler/217132"

biler <- url %>% 
  read_html() %>% 
  html_element("table") %>% 
  html_table() %>% 
  row_to_names(row_number = 1)

colnames(biler)[1] = "modell"
colnames(biler)[2] = "wltp"
colnames(biler)[3] = "stopp"

biler$wltp <- substr(biler$wltp, 0,3) %>% 
  as.numeric()
biler$stopp <- substr(biler$stopp,0,3) %>% 
  as.numeric()


```

```{r}
biler %>% 
  ggplot(aes(x=wltp, y=stopp))+
  geom_point()+
  geom_abline(intercept = 0,slope = 1)+
  scale_x_continuous(limits = c(200, 600))+
  scale_y_continuous(limits = c(200, 600))+
  xlab("Claimed range")+
  ylab("Real range")+
  ggtitle("Electric cars claimed range vs real life range")
```

## Task 2

```{r}
lm(stopp ~ wltp, data = biler) 
```

```{r}
biler %>% 
  ggplot(aes(x=wltp, y=stopp))+
  geom_point()+
  geom_abline(intercept = 0,slope = 1)+
  scale_x_continuous(limits = c(200, 600))+
  scale_y_continuous(limits = c(200, 600))+
  xlab("Claimed range")+
  ylab("Real range")+
  ggtitle("Electric cars claimed range vs real life range")+
  geom_smooth(method = lm)
```
